### ISSUE TITLE
Application crashes with certain problematic MOD files.

### ISSUE THREAD

**Issue by ferro4prez** [B0ney/xmodits#23]
![image](https://user-images.githubusercontent.com/28815173/217337146-5b509181-0fee-409c-a31d-b4986b22e8f9.png)

This happened on a subfolder "A" of the full modarchive torrent, and is reproducible on subsequent runs, but I can't identify the offending MOD (xm?) because of the crash.

**Comment by B0ney** [comment]
Oh? That's *very* interesting. I was convinced that the SoundTracker implementation was the culprit, but turns out it was from Extended Module 😅

If you're wondering how the XM format got involved despite ripping a folder of MODs:

* The loader uses the file's extension (``xm``, ``mod``, etc) to to determine which format to load first (unless overridden by "Hint").
* If this fails, it basically brute forces it by trying to load the remaining formats.
* If non of the formats can load the file, it is discarded and the original error is reported.

Fixing the crash is fairly easy to do. When I publish the hot-fix, you should have an easier time identifying the cursed "mod".

**Comment by ferro4prez** [comment]
Success!

It got through and listed the problem files, but no crash.

Thank you !

**Comment by B0ney** [comment]
Awesome! The file that previously crashed the program will now return this error:

```
This module has caused an out of bounds error. This is a bug. Please add this module to your bug report.
```

**Comment by ferro4prez** [comment]
This is great, thank you so much!

And if you do fix the sample-rate octave issue, happy to test anytime.
